version: "2"
services:
  app:
    container_name: back
    restart: always
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI
      - BACK_PORT
      - NODE_ENV
      - TOKEN_SECRET
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"